version: "2.1"

services:

  hello1:
    build: ./hello1
    container_name: hello1
    expose:
      - 80
  
  hello2:
    build: ./hello2
    container_name: hello2
    expose:
      - 80
  
  nginxlb:
    build: ./nginx
    container_name: nginxlb
    ports:
      - 80:80
      - 500:443
    depends_on:
      - hello1
      - hello2