---
- name: Remove Nginx Container
  hosts: localhost
  tasks:
    - name: Stop hello1 container
      docker_container:
        name: hello1
        state: absent
    
    - name: Stop hello2 container
      docker_container:
        name: hello2
        state: absent

    - name: Stop loadbalancer
      docker_container:
        name: nginxlb
        state: absent

    #- name: Remove loadbalancer image
    #  docker_image:
    #    state: absent
    #    name: nginxloadbalancer:latest
    #    tag: latest

    #- name: Remove hello1 image
    #  docker_image:
    #    state: absent
    #    name: hello:v1
    #    tag: latest

    #- name: Remove hello2 image
    #  docker_image:
    #    state: absent
    #    name: hello:v2
    #    tag: latest

    - name: remove nginxweb network
      docker_network:
        state: absent
        name: nginxweb