FROM nginx:latest
COPY conf/default.conf /etc/nginx/conf.d/default.conf
COPY /var/lib/docker/tmp/docker-builder000501750/localhost.pem /etc/nginx/localhost.pem
COPY /var/lib/docker/tmp/docker-builder000501750/localhost-key.pem /etc/nginx/localhost-key.pem